apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_network: "true"
        io.kompose.service: logstash
    spec:
      containers:
      - args:
        - logstash
        - -f
        - /etc/logstash/back_end/src/fileServiceMngr/app/logstash.conf
        image: docker.elastic.co/logstash/logstash:7.6.2
        imagePullPolicy: ""
        name: logstash
#        volumeMounts:
#          # name should match from volumes section
#          - name: logs-volume-1
#            mountPath: "/logs"
        ports:
        - containerPort: 9600
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
#      volumes:
#        - name: logs-volume-1
#          persistentVolumeClaim:
#            claimName: nfs-logs-pvc
status: {}
